root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/webui cmd/webui/main.go"
  bin = "./tmp/webui"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "html", "yaml"]
  exclude_regex = ["_test.go", ".bak"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"