// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/user"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) CreateUser(ctx context.Context, username string, password string, role int16) error {
	ret := _mock.Called(ctx, username, password, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int16) error); ok {
		r0 = returnFunc(ctx, username, password, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthUsecase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - role int16
func (_e *MockAuthUsecase_Expecter) CreateUser(ctx any, username any, password any, role any) *MockAuthUsecase_CreateUser_Call {
	return &MockAuthUsecase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, password, role)}
}

func (_c *MockAuthUsecase_CreateUser_Call) Run(run func(ctx context.Context, username string, password string, role int16)) *MockAuthUsecase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int16
		if args[3] != nil {
			arg3 = args[3].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_CreateUser_Call) Return(err error) *MockAuthUsecase_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_CreateUser_Call) RunAndReturn(run func(ctx context.Context, username string, password string, role int16) error) *MockAuthUsecase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthUsecase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthUsecase_Expecter) DeleteUser(ctx any, id any) *MockAuthUsecase_DeleteUser_Call {
	return &MockAuthUsecase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockAuthUsecase_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthUsecase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_DeleteUser_Call) Return(err error) *MockAuthUsecase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthUsecase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebExpireDuration provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) GetWebExpireDuration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWebExpireDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockAuthUsecase_GetWebExpireDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebExpireDuration'
type MockAuthUsecase_GetWebExpireDuration_Call struct {
	*mock.Call
}

// GetWebExpireDuration is a helper method to define mock.On call
func (_e *MockAuthUsecase_Expecter) GetWebExpireDuration() *MockAuthUsecase_GetWebExpireDuration_Call {
	return &MockAuthUsecase_GetWebExpireDuration_Call{Call: _e.mock.On("GetWebExpireDuration")}
}

func (_c *MockAuthUsecase_GetWebExpireDuration_Call) Run(run func()) *MockAuthUsecase_GetWebExpireDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthUsecase_GetWebExpireDuration_Call) Return(duration time.Duration) *MockAuthUsecase_GetWebExpireDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockAuthUsecase_GetWebExpireDuration_Call) RunAndReturn(run func() time.Duration) *MockAuthUsecase_GetWebExpireDuration_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) ListUsers(ctx context.Context) ([]user.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]user.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []user.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAuthUsecase_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthUsecase_Expecter) ListUsers(ctx any) *MockAuthUsecase_ListUsers_Call {
	return &MockAuthUsecase_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockAuthUsecase_ListUsers_Call) Run(run func(ctx context.Context)) *MockAuthUsecase_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_ListUsers_Call) Return(users []user.User, err error) *MockAuthUsecase_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAuthUsecase_ListUsers_Call) RunAndReturn(run func(ctx context.Context) ([]user.User, error)) *MockAuthUsecase_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthUsecase_Expecter) Login(ctx any, username any, password any) *MockAuthUsecase_Login_Call {
	return &MockAuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthUsecase_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_Login_Call) Return(token string, err error) *MockAuthUsecase_Login_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthUsecase_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockAuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginCLI provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) LoginCLI(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginCLI")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_LoginCLI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginCLI'
type MockAuthUsecase_LoginCLI_Call struct {
	*mock.Call
}

// LoginCLI is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthUsecase_Expecter) LoginCLI(ctx any, username any, password any) *MockAuthUsecase_LoginCLI_Call {
	return &MockAuthUsecase_LoginCLI_Call{Call: _e.mock.On("LoginCLI", ctx, username, password)}
}

func (_c *MockAuthUsecase_LoginCLI_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthUsecase_LoginCLI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_LoginCLI_Call) Return(token string, err error) *MockAuthUsecase_LoginCLI_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthUsecase_LoginCLI_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockAuthUsecase_LoginCLI_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) Logout(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthUsecase_Expecter) Logout(ctx any, token any) *MockAuthUsecase_Logout_Call {
	return &MockAuthUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *MockAuthUsecase_Logout_Call) Run(run func(ctx context.Context, token string)) *MockAuthUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_Logout_Call) Return(err error) *MockAuthUsecase_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_Logout_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) UpdateUserPassword(ctx context.Context, id uuid.UUID, password string) error {
	ret := _mock.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockAuthUsecase_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - password string
func (_e *MockAuthUsecase_Expecter) UpdateUserPassword(ctx any, id any, password any) *MockAuthUsecase_UpdateUserPassword_Call {
	return &MockAuthUsecase_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, id, password)}
}

func (_c *MockAuthUsecase_UpdateUserPassword_Call) Run(run func(ctx context.Context, id uuid.UUID, password string)) *MockAuthUsecase_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_UpdateUserPassword_Call) Return(err error) *MockAuthUsecase_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, password string) error) *MockAuthUsecase_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) UpdateUserStatus(ctx context.Context, id uuid.UUID, status int16) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int16) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type MockAuthUsecase_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status int16
func (_e *MockAuthUsecase_Expecter) UpdateUserStatus(ctx any, id any, status any) *MockAuthUsecase_UpdateUserStatus_Call {
	return &MockAuthUsecase_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, id, status)}
}

func (_c *MockAuthUsecase_UpdateUserStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status int16)) *MockAuthUsecase_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int16
		if args[2] != nil {
			arg2 = args[2].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_UpdateUserStatus_Call) Return(err error) *MockAuthUsecase_UpdateUserStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_UpdateUserStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status int16) error) *MockAuthUsecase_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) VerifyToken(ctx context.Context, token string) (*user.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockAuthUsecase_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthUsecase_Expecter) VerifyToken(ctx any, token any) *MockAuthUsecase_VerifyToken_Call {
	return &MockAuthUsecase_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockAuthUsecase_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthUsecase_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_VerifyToken_Call) Return(user1 *user.User, err error) *MockAuthUsecase_VerifyToken_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthUsecase_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*user.User, error)) *MockAuthUsecase_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
