// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/config"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigUsecase creates a new instance of MockConfigUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigUsecase {
	mock := &MockConfigUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigUsecase is an autogenerated mock type for the ConfigUsecase type
type MockConfigUsecase struct {
	mock.Mock
}

type MockConfigUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigUsecase) EXPECT() *MockConfigUsecase_Expecter {
	return &MockConfigUsecase_Expecter{mock: &_m.Mock}
}

// CreateConfig provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) CreateConfig(ctx context.Context, userID uuid.UUID, name string, tunnels config.TunnelsJSONB) error {
	ret := _mock.Called(ctx, userID, name, tunnels)

	if len(ret) == 0 {
		panic("no return value specified for CreateConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, config.TunnelsJSONB) error); ok {
		r0 = returnFunc(ctx, userID, name, tunnels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigUsecase_CreateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConfig'
type MockConfigUsecase_CreateConfig_Call struct {
	*mock.Call
}

// CreateConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
//   - tunnels config.TunnelsJSONB
func (_e *MockConfigUsecase_Expecter) CreateConfig(ctx any, userID any, name any, tunnels any) *MockConfigUsecase_CreateConfig_Call {
	return &MockConfigUsecase_CreateConfig_Call{Call: _e.mock.On("CreateConfig", ctx, userID, name, tunnels)}
}

func (_c *MockConfigUsecase_CreateConfig_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string, tunnels config.TunnelsJSONB)) *MockConfigUsecase_CreateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 config.TunnelsJSONB
		if args[3] != nil {
			arg3 = args[3].(config.TunnelsJSONB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_CreateConfig_Call) Return(err error) *MockConfigUsecase_CreateConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigUsecase_CreateConfig_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, name string, tunnels config.TunnelsJSONB) error) *MockConfigUsecase_CreateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConfig provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) DeleteConfig(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigUsecase_DeleteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConfig'
type MockConfigUsecase_DeleteConfig_Call struct {
	*mock.Call
}

// DeleteConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockConfigUsecase_Expecter) DeleteConfig(ctx any, id any) *MockConfigUsecase_DeleteConfig_Call {
	return &MockConfigUsecase_DeleteConfig_Call{Call: _e.mock.On("DeleteConfig", ctx, id)}
}

func (_c *MockConfigUsecase_DeleteConfig_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockConfigUsecase_DeleteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_DeleteConfig_Call) Return(err error) *MockConfigUsecase_DeleteConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigUsecase_DeleteConfig_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockConfigUsecase_DeleteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllConfigs provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) GetAllConfigs(ctx context.Context) ([]config.ClientConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllConfigs")
	}

	var r0 []config.ClientConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]config.ClientConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []config.ClientConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigUsecase_GetAllConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConfigs'
type MockConfigUsecase_GetAllConfigs_Call struct {
	*mock.Call
}

// GetAllConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigUsecase_Expecter) GetAllConfigs(ctx any) *MockConfigUsecase_GetAllConfigs_Call {
	return &MockConfigUsecase_GetAllConfigs_Call{Call: _e.mock.On("GetAllConfigs", ctx)}
}

func (_c *MockConfigUsecase_GetAllConfigs_Call) Run(run func(ctx context.Context)) *MockConfigUsecase_GetAllConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_GetAllConfigs_Call) Return(clientConfigs []config.ClientConfig, err error) *MockConfigUsecase_GetAllConfigs_Call {
	_c.Call.Return(clientConfigs, err)
	return _c
}

func (_c *MockConfigUsecase_GetAllConfigs_Call) RunAndReturn(run func(ctx context.Context) ([]config.ClientConfig, error)) *MockConfigUsecase_GetAllConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigByID provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) GetConfigByID(ctx context.Context, id uuid.UUID) (*config.ClientConfig, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigByID")
	}

	var r0 *config.ClientConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*config.ClientConfig, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *config.ClientConfig); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigUsecase_GetConfigByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigByID'
type MockConfigUsecase_GetConfigByID_Call struct {
	*mock.Call
}

// GetConfigByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockConfigUsecase_Expecter) GetConfigByID(ctx any, id any) *MockConfigUsecase_GetConfigByID_Call {
	return &MockConfigUsecase_GetConfigByID_Call{Call: _e.mock.On("GetConfigByID", ctx, id)}
}

func (_c *MockConfigUsecase_GetConfigByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockConfigUsecase_GetConfigByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_GetConfigByID_Call) Return(clientConfig *config.ClientConfig, err error) *MockConfigUsecase_GetConfigByID_Call {
	_c.Call.Return(clientConfig, err)
	return _c
}

func (_c *MockConfigUsecase_GetConfigByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*config.ClientConfig, error)) *MockConfigUsecase_GetConfigByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigByName provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) GetConfigByName(ctx context.Context, userID uuid.UUID, name string) (*config.ClientConfig, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigByName")
	}

	var r0 *config.ClientConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*config.ClientConfig, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *config.ClientConfig); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigUsecase_GetConfigByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigByName'
type MockConfigUsecase_GetConfigByName_Call struct {
	*mock.Call
}

// GetConfigByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
func (_e *MockConfigUsecase_Expecter) GetConfigByName(ctx any, userID any, name any) *MockConfigUsecase_GetConfigByName_Call {
	return &MockConfigUsecase_GetConfigByName_Call{Call: _e.mock.On("GetConfigByName", ctx, userID, name)}
}

func (_c *MockConfigUsecase_GetConfigByName_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string)) *MockConfigUsecase_GetConfigByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_GetConfigByName_Call) Return(clientConfig *config.ClientConfig, err error) *MockConfigUsecase_GetConfigByName_Call {
	_c.Call.Return(clientConfig, err)
	return _c
}

func (_c *MockConfigUsecase_GetConfigByName_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, name string) (*config.ClientConfig, error)) *MockConfigUsecase_GetConfigByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigsByUserID provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) GetConfigsByUserID(ctx context.Context, userID uuid.UUID) ([]config.ClientConfig, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigsByUserID")
	}

	var r0 []config.ClientConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]config.ClientConfig, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []config.ClientConfig); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigUsecase_GetConfigsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigsByUserID'
type MockConfigUsecase_GetConfigsByUserID_Call struct {
	*mock.Call
}

// GetConfigsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockConfigUsecase_Expecter) GetConfigsByUserID(ctx any, userID any) *MockConfigUsecase_GetConfigsByUserID_Call {
	return &MockConfigUsecase_GetConfigsByUserID_Call{Call: _e.mock.On("GetConfigsByUserID", ctx, userID)}
}

func (_c *MockConfigUsecase_GetConfigsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockConfigUsecase_GetConfigsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_GetConfigsByUserID_Call) Return(clientConfigs []config.ClientConfig, err error) *MockConfigUsecase_GetConfigsByUserID_Call {
	_c.Call.Return(clientConfigs, err)
	return _c
}

func (_c *MockConfigUsecase_GetConfigsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]config.ClientConfig, error)) *MockConfigUsecase_GetConfigsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConfig provides a mock function for the type MockConfigUsecase
func (_mock *MockConfigUsecase) UpdateConfig(ctx context.Context, id uuid.UUID, name string, tunnels config.TunnelsJSONB) error {
	ret := _mock.Called(ctx, id, name, tunnels)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, config.TunnelsJSONB) error); ok {
		r0 = returnFunc(ctx, id, name, tunnels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigUsecase_UpdateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConfig'
type MockConfigUsecase_UpdateConfig_Call struct {
	*mock.Call
}

// UpdateConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
//   - tunnels config.TunnelsJSONB
func (_e *MockConfigUsecase_Expecter) UpdateConfig(ctx any, id any, name any, tunnels any) *MockConfigUsecase_UpdateConfig_Call {
	return &MockConfigUsecase_UpdateConfig_Call{Call: _e.mock.On("UpdateConfig", ctx, id, name, tunnels)}
}

func (_c *MockConfigUsecase_UpdateConfig_Call) Run(run func(ctx context.Context, id uuid.UUID, name string, tunnels config.TunnelsJSONB)) *MockConfigUsecase_UpdateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 config.TunnelsJSONB
		if args[3] != nil {
			arg3 = args[3].(config.TunnelsJSONB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConfigUsecase_UpdateConfig_Call) Return(err error) *MockConfigUsecase_UpdateConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigUsecase_UpdateConfig_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, name string, tunnels config.TunnelsJSONB) error) *MockConfigUsecase_UpdateConfig_Call {
	_c.Call.Return(run)
	return _c
}
