// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/tunnel"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnelUsecase creates a new instance of MockTunnelUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnelUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnelUsecase {
	mock := &MockTunnelUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnelUsecase is an autogenerated mock type for the TunnelUsecase type
type MockTunnelUsecase struct {
	mock.Mock
}

type MockTunnelUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnelUsecase) EXPECT() *MockTunnelUsecase_Expecter {
	return &MockTunnelUsecase_Expecter{mock: &_m.Mock}
}

// AddDomain provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) AddDomain(ctx context.Context, domain string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, domain, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, domain, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_AddDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDomain'
type MockTunnelUsecase_AddDomain_Call struct {
	*mock.Call
}

// AddDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
func (_e *MockTunnelUsecase_Expecter) AddDomain(ctx any, domain any, userID any) *MockTunnelUsecase_AddDomain_Call {
	return &MockTunnelUsecase_AddDomain_Call{Call: _e.mock.On("AddDomain", ctx, domain, userID)}
}

func (_c *MockTunnelUsecase_AddDomain_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID)) *MockTunnelUsecase_AddDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_AddDomain_Call) Return(err error) *MockTunnelUsecase_AddDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_AddDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID) error) *MockTunnelUsecase_AddDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRateLimitSetting provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) DeleteRateLimitSetting(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRateLimitSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_DeleteRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRateLimitSetting'
type MockTunnelUsecase_DeleteRateLimitSetting_Call struct {
	*mock.Call
}

// DeleteRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockTunnelUsecase_Expecter) DeleteRateLimitSetting(ctx any, username any) *MockTunnelUsecase_DeleteRateLimitSetting_Call {
	return &MockTunnelUsecase_DeleteRateLimitSetting_Call{Call: _e.mock.On("DeleteRateLimitSetting", ctx, username)}
}

func (_c *MockTunnelUsecase_DeleteRateLimitSetting_Call) Run(run func(ctx context.Context, username string)) *MockTunnelUsecase_DeleteRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_DeleteRateLimitSetting_Call) Return(err error) *MockTunnelUsecase_DeleteRateLimitSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_DeleteRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string) error) *MockTunnelUsecase_DeleteRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// FlushAllTunnelsAndDomains provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) FlushAllTunnelsAndDomains(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushAllTunnelsAndDomains")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_FlushAllTunnelsAndDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushAllTunnelsAndDomains'
type MockTunnelUsecase_FlushAllTunnelsAndDomains_Call struct {
	*mock.Call
}

// FlushAllTunnelsAndDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelUsecase_Expecter) FlushAllTunnelsAndDomains(ctx any) *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call {
	return &MockTunnelUsecase_FlushAllTunnelsAndDomains_Call{Call: _e.mock.On("FlushAllTunnelsAndDomains", ctx)}
}

func (_c *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call) Run(run func(ctx context.Context)) *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call) Return(err error) *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call) RunAndReturn(run func(ctx context.Context) error) *MockTunnelUsecase_FlushAllTunnelsAndDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimitSetting provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) GetRateLimitSetting(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimitSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_GetRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimitSetting'
type MockTunnelUsecase_GetRateLimitSetting_Call struct {
	*mock.Call
}

// GetRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockTunnelUsecase_Expecter) GetRateLimitSetting(ctx any, username any) *MockTunnelUsecase_GetRateLimitSetting_Call {
	return &MockTunnelUsecase_GetRateLimitSetting_Call{Call: _e.mock.On("GetRateLimitSetting", ctx, username)}
}

func (_c *MockTunnelUsecase_GetRateLimitSetting_Call) Run(run func(ctx context.Context, username string)) *MockTunnelUsecase_GetRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_GetRateLimitSetting_Call) Return(s string, err error) *MockTunnelUsecase_GetRateLimitSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTunnelUsecase_GetRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockTunnelUsecase_GetRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// IsDomainAllowed provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) IsDomainAllowed(ctx context.Context, domain string, userID uuid.UUID, role int16) (bool, error) {
	ret := _mock.Called(ctx, domain, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for IsDomainAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) (bool, error)); ok {
		return returnFunc(ctx, domain, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) bool); ok {
		r0 = returnFunc(ctx, domain, userID, role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int16) error); ok {
		r1 = returnFunc(ctx, domain, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_IsDomainAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDomainAllowed'
type MockTunnelUsecase_IsDomainAllowed_Call struct {
	*mock.Call
}

// IsDomainAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
//   - role int16
func (_e *MockTunnelUsecase_Expecter) IsDomainAllowed(ctx any, domain any, userID any, role any) *MockTunnelUsecase_IsDomainAllowed_Call {
	return &MockTunnelUsecase_IsDomainAllowed_Call{Call: _e.mock.On("IsDomainAllowed", ctx, domain, userID, role)}
}

func (_c *MockTunnelUsecase_IsDomainAllowed_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID, role int16)) *MockTunnelUsecase_IsDomainAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int16
		if args[3] != nil {
			arg3 = args[3].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_IsDomainAllowed_Call) Return(b bool, err error) *MockTunnelUsecase_IsDomainAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTunnelUsecase_IsDomainAllowed_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID, role int16) (bool, error)) *MockTunnelUsecase_IsDomainAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomains provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) ListDomains(ctx context.Context, userID uuid.UUID, role int16) ([]tunnel.Domain, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ListDomains")
	}

	var r0 []tunnel.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int16) ([]tunnel.Domain, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int16) []tunnel.Domain); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int16) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_ListDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomains'
type MockTunnelUsecase_ListDomains_Call struct {
	*mock.Call
}

// ListDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - role int16
func (_e *MockTunnelUsecase_Expecter) ListDomains(ctx any, userID any, role any) *MockTunnelUsecase_ListDomains_Call {
	return &MockTunnelUsecase_ListDomains_Call{Call: _e.mock.On("ListDomains", ctx, userID, role)}
}

func (_c *MockTunnelUsecase_ListDomains_Call) Run(run func(ctx context.Context, userID uuid.UUID, role int16)) *MockTunnelUsecase_ListDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int16
		if args[2] != nil {
			arg2 = args[2].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_ListDomains_Call) Return(domains []tunnel.Domain, err error) *MockTunnelUsecase_ListDomains_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *MockTunnelUsecase_ListDomains_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, role int16) ([]tunnel.Domain, error)) *MockTunnelUsecase_ListDomains_Call {
	_c.Call.Return(run)
	return _c
}

// ListTunnels provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) ListTunnels(ctx context.Context) ([]tunnel.TunnelInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTunnels")
	}

	var r0 []tunnel.TunnelInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]tunnel.TunnelInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []tunnel.TunnelInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.TunnelInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_ListTunnels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTunnels'
type MockTunnelUsecase_ListTunnels_Call struct {
	*mock.Call
}

// ListTunnels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelUsecase_Expecter) ListTunnels(ctx any) *MockTunnelUsecase_ListTunnels_Call {
	return &MockTunnelUsecase_ListTunnels_Call{Call: _e.mock.On("ListTunnels", ctx)}
}

func (_c *MockTunnelUsecase_ListTunnels_Call) Run(run func(ctx context.Context)) *MockTunnelUsecase_ListTunnels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_ListTunnels_Call) Return(tunnelInfos []tunnel.TunnelInfo, err error) *MockTunnelUsecase_ListTunnels_Call {
	_c.Call.Return(tunnelInfos, err)
	return _c
}

func (_c *MockTunnelUsecase_ListTunnels_Call) RunAndReturn(run func(ctx context.Context) ([]tunnel.TunnelInfo, error)) *MockTunnelUsecase_ListTunnels_Call {
	_c.Call.Return(run)
	return _c
}

// PublishInspectEvent provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) PublishInspectEvent(ctx context.Context, host string, payload string) error {
	ret := _mock.Called(ctx, host, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishInspectEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, host, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_PublishInspectEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishInspectEvent'
type MockTunnelUsecase_PublishInspectEvent_Call struct {
	*mock.Call
}

// PublishInspectEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
//   - payload string
func (_e *MockTunnelUsecase_Expecter) PublishInspectEvent(ctx any, host any, payload any) *MockTunnelUsecase_PublishInspectEvent_Call {
	return &MockTunnelUsecase_PublishInspectEvent_Call{Call: _e.mock.On("PublishInspectEvent", ctx, host, payload)}
}

func (_c *MockTunnelUsecase_PublishInspectEvent_Call) Run(run func(ctx context.Context, host string, payload string)) *MockTunnelUsecase_PublishInspectEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_PublishInspectEvent_Call) Return(err error) *MockTunnelUsecase_PublishInspectEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_PublishInspectEvent_Call) RunAndReturn(run func(ctx context.Context, host string, payload string) error) *MockTunnelUsecase_PublishInspectEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PublishTunnelEvent provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) PublishTunnelEvent(ctx context.Context, eventType string) error {
	ret := _mock.Called(ctx, eventType)

	if len(ret) == 0 {
		panic("no return value specified for PublishTunnelEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, eventType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_PublishTunnelEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTunnelEvent'
type MockTunnelUsecase_PublishTunnelEvent_Call struct {
	*mock.Call
}

// PublishTunnelEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
func (_e *MockTunnelUsecase_Expecter) PublishTunnelEvent(ctx any, eventType any) *MockTunnelUsecase_PublishTunnelEvent_Call {
	return &MockTunnelUsecase_PublishTunnelEvent_Call{Call: _e.mock.On("PublishTunnelEvent", ctx, eventType)}
}

func (_c *MockTunnelUsecase_PublishTunnelEvent_Call) Run(run func(ctx context.Context, eventType string)) *MockTunnelUsecase_PublishTunnelEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_PublishTunnelEvent_Call) Return(err error) *MockTunnelUsecase_PublishTunnelEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_PublishTunnelEvent_Call) RunAndReturn(run func(ctx context.Context, eventType string) error) *MockTunnelUsecase_PublishTunnelEvent_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshActiveDomains provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) RefreshActiveDomains(ctx context.Context, domains []string, sessionID string, ttl time.Duration) error {
	ret := _mock.Called(ctx, domains, sessionID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RefreshActiveDomains")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, domains, sessionID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_RefreshActiveDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshActiveDomains'
type MockTunnelUsecase_RefreshActiveDomains_Call struct {
	*mock.Call
}

// RefreshActiveDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - domains []string
//   - sessionID string
//   - ttl time.Duration
func (_e *MockTunnelUsecase_Expecter) RefreshActiveDomains(ctx any, domains any, sessionID any, ttl any) *MockTunnelUsecase_RefreshActiveDomains_Call {
	return &MockTunnelUsecase_RefreshActiveDomains_Call{Call: _e.mock.On("RefreshActiveDomains", ctx, domains, sessionID, ttl)}
}

func (_c *MockTunnelUsecase_RefreshActiveDomains_Call) Run(run func(ctx context.Context, domains []string, sessionID string, ttl time.Duration)) *MockTunnelUsecase_RefreshActiveDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_RefreshActiveDomains_Call) Return(err error) *MockTunnelUsecase_RefreshActiveDomains_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_RefreshActiveDomains_Call) RunAndReturn(run func(ctx context.Context, domains []string, sessionID string, ttl time.Duration) error) *MockTunnelUsecase_RefreshActiveDomains_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterTunnel provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) RegisterTunnel(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error {
	ret := _mock.Called(ctx, sessionID, info)

	if len(ret) == 0 {
		panic("no return value specified for RegisterTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, tunnel.TunnelInfo) error); ok {
		r0 = returnFunc(ctx, sessionID, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_RegisterTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTunnel'
type MockTunnelUsecase_RegisterTunnel_Call struct {
	*mock.Call
}

// RegisterTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - info tunnel.TunnelInfo
func (_e *MockTunnelUsecase_Expecter) RegisterTunnel(ctx any, sessionID any, info any) *MockTunnelUsecase_RegisterTunnel_Call {
	return &MockTunnelUsecase_RegisterTunnel_Call{Call: _e.mock.On("RegisterTunnel", ctx, sessionID, info)}
}

func (_c *MockTunnelUsecase_RegisterTunnel_Call) Run(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo)) *MockTunnelUsecase_RegisterTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 tunnel.TunnelInfo
		if args[2] != nil {
			arg2 = args[2].(tunnel.TunnelInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_RegisterTunnel_Call) Return(err error) *MockTunnelUsecase_RegisterTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_RegisterTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error) *MockTunnelUsecase_RegisterTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveActiveDomain provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) RemoveActiveDomain(ctx context.Context, domain string) error {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for RemoveActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_RemoveActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveActiveDomain'
type MockTunnelUsecase_RemoveActiveDomain_Call struct {
	*mock.Call
}

// RemoveActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockTunnelUsecase_Expecter) RemoveActiveDomain(ctx any, domain any) *MockTunnelUsecase_RemoveActiveDomain_Call {
	return &MockTunnelUsecase_RemoveActiveDomain_Call{Call: _e.mock.On("RemoveActiveDomain", ctx, domain)}
}

func (_c *MockTunnelUsecase_RemoveActiveDomain_Call) Run(run func(ctx context.Context, domain string)) *MockTunnelUsecase_RemoveActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_RemoveActiveDomain_Call) Return(err error) *MockTunnelUsecase_RemoveActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_RemoveActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string) error) *MockTunnelUsecase_RemoveActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDomain provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) RemoveDomain(ctx context.Context, domain string, userID uuid.UUID, role int16) error {
	ret := _mock.Called(ctx, domain, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) error); ok {
		r0 = returnFunc(ctx, domain, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_RemoveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDomain'
type MockTunnelUsecase_RemoveDomain_Call struct {
	*mock.Call
}

// RemoveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
//   - role int16
func (_e *MockTunnelUsecase_Expecter) RemoveDomain(ctx any, domain any, userID any, role any) *MockTunnelUsecase_RemoveDomain_Call {
	return &MockTunnelUsecase_RemoveDomain_Call{Call: _e.mock.On("RemoveDomain", ctx, domain, userID, role)}
}

func (_c *MockTunnelUsecase_RemoveDomain_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID, role int16)) *MockTunnelUsecase_RemoveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int16
		if args[3] != nil {
			arg3 = args[3].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_RemoveDomain_Call) Return(err error) *MockTunnelUsecase_RemoveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_RemoveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID, role int16) error) *MockTunnelUsecase_RemoveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveDomain provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) SetActiveDomain(ctx context.Context, domain string, sessionID string) error {
	ret := _mock.Called(ctx, domain, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, domain, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_SetActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveDomain'
type MockTunnelUsecase_SetActiveDomain_Call struct {
	*mock.Call
}

// SetActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - sessionID string
func (_e *MockTunnelUsecase_Expecter) SetActiveDomain(ctx any, domain any, sessionID any) *MockTunnelUsecase_SetActiveDomain_Call {
	return &MockTunnelUsecase_SetActiveDomain_Call{Call: _e.mock.On("SetActiveDomain", ctx, domain, sessionID)}
}

func (_c *MockTunnelUsecase_SetActiveDomain_Call) Run(run func(ctx context.Context, domain string, sessionID string)) *MockTunnelUsecase_SetActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_SetActiveDomain_Call) Return(err error) *MockTunnelUsecase_SetActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_SetActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, sessionID string) error) *MockTunnelUsecase_SetActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// SetRateLimitSetting provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) SetRateLimitSetting(ctx context.Context, username string, value string) error {
	ret := _mock.Called(ctx, username, value)

	if len(ret) == 0 {
		panic("no return value specified for SetRateLimitSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_SetRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRateLimitSetting'
type MockTunnelUsecase_SetRateLimitSetting_Call struct {
	*mock.Call
}

// SetRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - value string
func (_e *MockTunnelUsecase_Expecter) SetRateLimitSetting(ctx any, username any, value any) *MockTunnelUsecase_SetRateLimitSetting_Call {
	return &MockTunnelUsecase_SetRateLimitSetting_Call{Call: _e.mock.On("SetRateLimitSetting", ctx, username, value)}
}

func (_c *MockTunnelUsecase_SetRateLimitSetting_Call) Run(run func(ctx context.Context, username string, value string)) *MockTunnelUsecase_SetRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_SetRateLimitSetting_Call) Return(err error) *MockTunnelUsecase_SetRateLimitSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_SetRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string, value string) error) *MockTunnelUsecase_SetRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeInspectEvents provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) SubscribeInspectEvents(ctx context.Context, hosts ...string) (<-chan string, error) {
	var tmpRet mock.Arguments
	if len(hosts) > 0 {
		tmpRet = _mock.Called(ctx, hosts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SubscribeInspectEvents")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (<-chan string, error)); ok {
		return returnFunc(ctx, hosts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) <-chan string); ok {
		r0 = returnFunc(ctx, hosts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, hosts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_SubscribeInspectEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeInspectEvents'
type MockTunnelUsecase_SubscribeInspectEvents_Call struct {
	*mock.Call
}

// SubscribeInspectEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - hosts ...string
func (_e *MockTunnelUsecase_Expecter) SubscribeInspectEvents(ctx any, hosts ...any) *MockTunnelUsecase_SubscribeInspectEvents_Call {
	return &MockTunnelUsecase_SubscribeInspectEvents_Call{Call: _e.mock.On("SubscribeInspectEvents",
		append([]any{ctx}, hosts...)...)}
}

func (_c *MockTunnelUsecase_SubscribeInspectEvents_Call) Run(run func(ctx context.Context, hosts ...string)) *MockTunnelUsecase_SubscribeInspectEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_SubscribeInspectEvents_Call) Return(stringCh <-chan string, err error) *MockTunnelUsecase_SubscribeInspectEvents_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockTunnelUsecase_SubscribeInspectEvents_Call) RunAndReturn(run func(ctx context.Context, hosts ...string) (<-chan string, error)) *MockTunnelUsecase_SubscribeInspectEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTunnelEvents provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) SubscribeTunnelEvents(ctx context.Context) (<-chan string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTunnelEvents")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelUsecase_SubscribeTunnelEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTunnelEvents'
type MockTunnelUsecase_SubscribeTunnelEvents_Call struct {
	*mock.Call
}

// SubscribeTunnelEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelUsecase_Expecter) SubscribeTunnelEvents(ctx any) *MockTunnelUsecase_SubscribeTunnelEvents_Call {
	return &MockTunnelUsecase_SubscribeTunnelEvents_Call{Call: _e.mock.On("SubscribeTunnelEvents", ctx)}
}

func (_c *MockTunnelUsecase_SubscribeTunnelEvents_Call) Run(run func(ctx context.Context)) *MockTunnelUsecase_SubscribeTunnelEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_SubscribeTunnelEvents_Call) Return(stringCh <-chan string, err error) *MockTunnelUsecase_SubscribeTunnelEvents_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockTunnelUsecase_SubscribeTunnelEvents_Call) RunAndReturn(run func(ctx context.Context) (<-chan string, error)) *MockTunnelUsecase_SubscribeTunnelEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterTunnel provides a mock function for the type MockTunnelUsecase
func (_mock *MockTunnelUsecase) UnregisterTunnel(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelUsecase_UnregisterTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterTunnel'
type MockTunnelUsecase_UnregisterTunnel_Call struct {
	*mock.Call
}

// UnregisterTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockTunnelUsecase_Expecter) UnregisterTunnel(ctx any, sessionID any) *MockTunnelUsecase_UnregisterTunnel_Call {
	return &MockTunnelUsecase_UnregisterTunnel_Call{Call: _e.mock.On("UnregisterTunnel", ctx, sessionID)}
}

func (_c *MockTunnelUsecase_UnregisterTunnel_Call) Run(run func(ctx context.Context, sessionID string)) *MockTunnelUsecase_UnregisterTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelUsecase_UnregisterTunnel_Call) Return(err error) *MockTunnelUsecase_UnregisterTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelUsecase_UnregisterTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockTunnelUsecase_UnregisterTunnel_Call {
	_c.Call.Return(run)
	return _c
}
