// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingStore creates a new instance of MockSettingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingStore {
	mock := &MockSettingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingStore is an autogenerated mock type for the SettingStore type
type MockSettingStore struct {
	mock.Mock
}

type MockSettingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingStore) EXPECT() *MockSettingStore_Expecter {
	return &MockSettingStore_Expecter{mock: &_m.Mock}
}

// GetAllSettings provides a mock function for the type MockSettingStore
func (_mock *MockSettingStore) GetAllSettings(ctx context.Context) (map[string]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingStore_GetAllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSettings'
type MockSettingStore_GetAllSettings_Call struct {
	*mock.Call
}

// GetAllSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingStore_Expecter) GetAllSettings(ctx any) *MockSettingStore_GetAllSettings_Call {
	return &MockSettingStore_GetAllSettings_Call{Call: _e.mock.On("GetAllSettings", ctx)}
}

func (_c *MockSettingStore_GetAllSettings_Call) Run(run func(ctx context.Context)) *MockSettingStore_GetAllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettingStore_GetAllSettings_Call) Return(stringToString map[string]string, err error) *MockSettingStore_GetAllSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockSettingStore_GetAllSettings_Call) RunAndReturn(run func(ctx context.Context) (map[string]string, error)) *MockSettingStore_GetAllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockSettingStore
func (_mock *MockSettingStore) GetSetting(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingStore_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockSettingStore_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSettingStore_Expecter) GetSetting(ctx any, key any) *MockSettingStore_GetSetting_Call {
	return &MockSettingStore_GetSetting_Call{Call: _e.mock.On("GetSetting", ctx, key)}
}

func (_c *MockSettingStore_GetSetting_Call) Run(run func(ctx context.Context, key string)) *MockSettingStore_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingStore_GetSetting_Call) Return(s string, err error) *MockSettingStore_GetSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSettingStore_GetSetting_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockSettingStore_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockSettingStore
func (_mock *MockSettingStore) SetSetting(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingStore_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockSettingStore_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockSettingStore_Expecter) SetSetting(ctx any, key any, value any) *MockSettingStore_SetSetting_Call {
	return &MockSettingStore_SetSetting_Call{Call: _e.mock.On("SetSetting", ctx, key, value)}
}

func (_c *MockSettingStore_SetSetting_Call) Run(run func(ctx context.Context, key string, value string)) *MockSettingStore_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSettingStore_SetSetting_Call) Return(err error) *MockSettingStore_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingStore_SetSetting_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockSettingStore_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}
