// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingUsecase creates a new instance of MockSettingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingUsecase {
	mock := &MockSettingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingUsecase is an autogenerated mock type for the SettingUsecase type
type MockSettingUsecase struct {
	mock.Mock
}

type MockSettingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingUsecase) EXPECT() *MockSettingUsecase_Expecter {
	return &MockSettingUsecase_Expecter{mock: &_m.Mock}
}

// GetAllSettings provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) GetAllSettings(ctx context.Context) (map[string]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingUsecase_GetAllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSettings'
type MockSettingUsecase_GetAllSettings_Call struct {
	*mock.Call
}

// GetAllSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingUsecase_Expecter) GetAllSettings(ctx any) *MockSettingUsecase_GetAllSettings_Call {
	return &MockSettingUsecase_GetAllSettings_Call{Call: _e.mock.On("GetAllSettings", ctx)}
}

func (_c *MockSettingUsecase_GetAllSettings_Call) Run(run func(ctx context.Context)) *MockSettingUsecase_GetAllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_GetAllSettings_Call) Return(stringToString map[string]string, err error) *MockSettingUsecase_GetAllSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockSettingUsecase_GetAllSettings_Call) RunAndReturn(run func(ctx context.Context) (map[string]string, error)) *MockSettingUsecase_GetAllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllowRegistration provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) GetAllowRegistration(ctx context.Context, fallback bool) bool {
	ret := _mock.Called(ctx, fallback)

	if len(ret) == 0 {
		panic("no return value specified for GetAllowRegistration")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) bool); ok {
		r0 = returnFunc(ctx, fallback)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSettingUsecase_GetAllowRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllowRegistration'
type MockSettingUsecase_GetAllowRegistration_Call struct {
	*mock.Call
}

// GetAllowRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - fallback bool
func (_e *MockSettingUsecase_Expecter) GetAllowRegistration(ctx any, fallback any) *MockSettingUsecase_GetAllowRegistration_Call {
	return &MockSettingUsecase_GetAllowRegistration_Call{Call: _e.mock.On("GetAllowRegistration", ctx, fallback)}
}

func (_c *MockSettingUsecase_GetAllowRegistration_Call) Run(run func(ctx context.Context, fallback bool)) *MockSettingUsecase_GetAllowRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_GetAllowRegistration_Call) Return(b bool) *MockSettingUsecase_GetAllowRegistration_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSettingUsecase_GetAllowRegistration_Call) RunAndReturn(run func(ctx context.Context, fallback bool) bool) *MockSettingUsecase_GetAllowRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxFreeDomains provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) GetMaxFreeDomains(ctx context.Context, fallback int) int {
	ret := _mock.Called(ctx, fallback)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxFreeDomains")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, fallback)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockSettingUsecase_GetMaxFreeDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxFreeDomains'
type MockSettingUsecase_GetMaxFreeDomains_Call struct {
	*mock.Call
}

// GetMaxFreeDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - fallback int
func (_e *MockSettingUsecase_Expecter) GetMaxFreeDomains(ctx any, fallback any) *MockSettingUsecase_GetMaxFreeDomains_Call {
	return &MockSettingUsecase_GetMaxFreeDomains_Call{Call: _e.mock.On("GetMaxFreeDomains", ctx, fallback)}
}

func (_c *MockSettingUsecase_GetMaxFreeDomains_Call) Run(run func(ctx context.Context, fallback int)) *MockSettingUsecase_GetMaxFreeDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_GetMaxFreeDomains_Call) Return(n int) *MockSettingUsecase_GetMaxFreeDomains_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSettingUsecase_GetMaxFreeDomains_Call) RunAndReturn(run func(ctx context.Context, fallback int) int) *MockSettingUsecase_GetMaxFreeDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxTunnelsPerUser provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) GetMaxTunnelsPerUser(ctx context.Context, fallback int) int {
	ret := _mock.Called(ctx, fallback)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxTunnelsPerUser")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, fallback)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockSettingUsecase_GetMaxTunnelsPerUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxTunnelsPerUser'
type MockSettingUsecase_GetMaxTunnelsPerUser_Call struct {
	*mock.Call
}

// GetMaxTunnelsPerUser is a helper method to define mock.On call
//   - ctx context.Context
//   - fallback int
func (_e *MockSettingUsecase_Expecter) GetMaxTunnelsPerUser(ctx any, fallback any) *MockSettingUsecase_GetMaxTunnelsPerUser_Call {
	return &MockSettingUsecase_GetMaxTunnelsPerUser_Call{Call: _e.mock.On("GetMaxTunnelsPerUser", ctx, fallback)}
}

func (_c *MockSettingUsecase_GetMaxTunnelsPerUser_Call) Run(run func(ctx context.Context, fallback int)) *MockSettingUsecase_GetMaxTunnelsPerUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_GetMaxTunnelsPerUser_Call) Return(n int) *MockSettingUsecase_GetMaxTunnelsPerUser_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSettingUsecase_GetMaxTunnelsPerUser_Call) RunAndReturn(run func(ctx context.Context, fallback int) int) *MockSettingUsecase_GetMaxTunnelsPerUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) GetSetting(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingUsecase_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockSettingUsecase_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSettingUsecase_Expecter) GetSetting(ctx any, key any) *MockSettingUsecase_GetSetting_Call {
	return &MockSettingUsecase_GetSetting_Call{Call: _e.mock.On("GetSetting", ctx, key)}
}

func (_c *MockSettingUsecase_GetSetting_Call) Run(run func(ctx context.Context, key string)) *MockSettingUsecase_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_GetSetting_Call) Return(s string, err error) *MockSettingUsecase_GetSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSettingUsecase_GetSetting_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockSettingUsecase_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockSettingUsecase
func (_mock *MockSettingUsecase) SetSetting(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingUsecase_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockSettingUsecase_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockSettingUsecase_Expecter) SetSetting(ctx any, key any, value any) *MockSettingUsecase_SetSetting_Call {
	return &MockSettingUsecase_SetSetting_Call{Call: _e.mock.On("SetSetting", ctx, key, value)}
}

func (_c *MockSettingUsecase_SetSetting_Call) Run(run func(ctx context.Context, key string, value string)) *MockSettingUsecase_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSettingUsecase_SetSetting_Call) Return(err error) *MockSettingUsecase_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingUsecase_SetSetting_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockSettingUsecase_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}
