// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/tunnel"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnelStore creates a new instance of MockTunnelStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnelStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnelStore {
	mock := &MockTunnelStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnelStore is an autogenerated mock type for the TunnelStore type
type MockTunnelStore struct {
	mock.Mock
}

type MockTunnelStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnelStore) EXPECT() *MockTunnelStore_Expecter {
	return &MockTunnelStore_Expecter{mock: &_m.Mock}
}

// DeleteTunnel provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) DeleteTunnel(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_DeleteTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTunnel'
type MockTunnelStore_DeleteTunnel_Call struct {
	*mock.Call
}

// DeleteTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockTunnelStore_Expecter) DeleteTunnel(ctx any, sessionID any) *MockTunnelStore_DeleteTunnel_Call {
	return &MockTunnelStore_DeleteTunnel_Call{Call: _e.mock.On("DeleteTunnel", ctx, sessionID)}
}

func (_c *MockTunnelStore_DeleteTunnel_Call) Run(run func(ctx context.Context, sessionID string)) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_DeleteTunnel_Call) Return(err error) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_DeleteTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockTunnelStore_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTunnelStore_Expecter) IsTokenRevoked(ctx any, token any) *MockTunnelStore_IsTokenRevoked_Call {
	return &MockTunnelStore_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, token)}
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) Run(run func(ctx context.Context, token string)) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) Return(b bool, err error) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ListTunnels provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) ListTunnels(ctx context.Context) ([]tunnel.TunnelInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTunnels")
	}

	var r0 []tunnel.TunnelInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]tunnel.TunnelInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []tunnel.TunnelInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.TunnelInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_ListTunnels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTunnels'
type MockTunnelStore_ListTunnels_Call struct {
	*mock.Call
}

// ListTunnels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) ListTunnels(ctx any) *MockTunnelStore_ListTunnels_Call {
	return &MockTunnelStore_ListTunnels_Call{Call: _e.mock.On("ListTunnels", ctx)}
}

func (_c *MockTunnelStore_ListTunnels_Call) Run(run func(ctx context.Context)) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_ListTunnels_Call) Return(tunnelInfos []tunnel.TunnelInfo, err error) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Return(tunnelInfos, err)
	return _c
}

func (_c *MockTunnelStore_ListTunnels_Call) RunAndReturn(run func(ctx context.Context) ([]tunnel.TunnelInfo, error)) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) Ping(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTunnelStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockTunnelStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) Ping(ctx any) *MockTunnelStore_Ping_Call {
	return &MockTunnelStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockTunnelStore_Ping_Call) Run(run func(ctx context.Context)) *MockTunnelStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_Ping_Call) Return() *MockTunnelStore_Ping_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTunnelStore_Ping_Call) RunAndReturn(run func(ctx context.Context)) *MockTunnelStore_Ping_Call {
	_c.Run(run)
	return _c
}

// RemoveActiveDomain provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RemoveActiveDomain(ctx context.Context, domain string) error {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for RemoveActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RemoveActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveActiveDomain'
type MockTunnelStore_RemoveActiveDomain_Call struct {
	*mock.Call
}

// RemoveActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockTunnelStore_Expecter) RemoveActiveDomain(ctx any, domain any) *MockTunnelStore_RemoveActiveDomain_Call {
	return &MockTunnelStore_RemoveActiveDomain_Call{Call: _e.mock.On("RemoveActiveDomain", ctx, domain)}
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) Run(run func(ctx context.Context, domain string)) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) Return(err error) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string) error) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RevokeToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockTunnelStore_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTunnelStore_Expecter) RevokeToken(ctx any, token any) *MockTunnelStore_RevokeToken_Call {
	return &MockTunnelStore_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, token)}
}

func (_c *MockTunnelStore_RevokeToken_Call) Run(run func(ctx context.Context, token string)) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RevokeToken_Call) Return(err error) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveDomain provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetActiveDomain(ctx context.Context, domain string, sessionID string) error {
	ret := _mock.Called(ctx, domain, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, domain, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveDomain'
type MockTunnelStore_SetActiveDomain_Call struct {
	*mock.Call
}

// SetActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - sessionID string
func (_e *MockTunnelStore_Expecter) SetActiveDomain(ctx any, domain any, sessionID any) *MockTunnelStore_SetActiveDomain_Call {
	return &MockTunnelStore_SetActiveDomain_Call{Call: _e.mock.On("SetActiveDomain", ctx, domain, sessionID)}
}

func (_c *MockTunnelStore_SetActiveDomain_Call) Run(run func(ctx context.Context, domain string, sessionID string)) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetActiveDomain_Call) Return(err error) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, sessionID string) error) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// SetToken provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetToken(ctx context.Context, token string, expiration time.Duration) error {
	ret := _mock.Called(ctx, token, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type MockTunnelStore_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expiration time.Duration
func (_e *MockTunnelStore_Expecter) SetToken(ctx any, token any, expiration any) *MockTunnelStore_SetToken_Call {
	return &MockTunnelStore_SetToken_Call{Call: _e.mock.On("SetToken", ctx, token, expiration)}
}

func (_c *MockTunnelStore_SetToken_Call) Run(run func(ctx context.Context, token string, expiration time.Duration)) *MockTunnelStore_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetToken_Call) Return(err error) *MockTunnelStore_SetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetToken_Call) RunAndReturn(run func(ctx context.Context, token string, expiration time.Duration) error) *MockTunnelStore_SetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetTunnel provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetTunnel(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error {
	ret := _mock.Called(ctx, sessionID, info)

	if len(ret) == 0 {
		panic("no return value specified for SetTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, tunnel.TunnelInfo) error); ok {
		r0 = returnFunc(ctx, sessionID, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTunnel'
type MockTunnelStore_SetTunnel_Call struct {
	*mock.Call
}

// SetTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - info tunnel.TunnelInfo
func (_e *MockTunnelStore_Expecter) SetTunnel(ctx any, sessionID any, info any) *MockTunnelStore_SetTunnel_Call {
	return &MockTunnelStore_SetTunnel_Call{Call: _e.mock.On("SetTunnel", ctx, sessionID, info)}
}

func (_c *MockTunnelStore_SetTunnel_Call) Run(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo)) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 tunnel.TunnelInfo
		if args[2] != nil {
			arg2 = args[2].(tunnel.TunnelInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetTunnel_Call) Return(err error) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Return(run)
	return _c
}
