// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/tunnel"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDomainStore creates a new instance of MockDomainStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainStore {
	mock := &MockDomainStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDomainStore is an autogenerated mock type for the DomainStore type
type MockDomainStore struct {
	mock.Mock
}

type MockDomainStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainStore) EXPECT() *MockDomainStore_Expecter {
	return &MockDomainStore_Expecter{mock: &_m.Mock}
}

// AddDomain provides a mock function for the type MockDomainStore
func (_mock *MockDomainStore) AddDomain(ctx context.Context, domain string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, domain, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, domain, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainStore_AddDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDomain'
type MockDomainStore_AddDomain_Call struct {
	*mock.Call
}

// AddDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
func (_e *MockDomainStore_Expecter) AddDomain(ctx any, domain any, userID any) *MockDomainStore_AddDomain_Call {
	return &MockDomainStore_AddDomain_Call{Call: _e.mock.On("AddDomain", ctx, domain, userID)}
}

func (_c *MockDomainStore_AddDomain_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID)) *MockDomainStore_AddDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDomainStore_AddDomain_Call) Return(err error) *MockDomainStore_AddDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainStore_AddDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID) error) *MockDomainStore_AddDomain_Call {
	_c.Call.Return(run)
	return _c
}

// IsDomainAllowed provides a mock function for the type MockDomainStore
func (_mock *MockDomainStore) IsDomainAllowed(ctx context.Context, domain string, userID uuid.UUID, role int16) (bool, error) {
	ret := _mock.Called(ctx, domain, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for IsDomainAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) (bool, error)); ok {
		return returnFunc(ctx, domain, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) bool); ok {
		r0 = returnFunc(ctx, domain, userID, role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int16) error); ok {
		r1 = returnFunc(ctx, domain, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainStore_IsDomainAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDomainAllowed'
type MockDomainStore_IsDomainAllowed_Call struct {
	*mock.Call
}

// IsDomainAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
//   - role int16
func (_e *MockDomainStore_Expecter) IsDomainAllowed(ctx any, domain any, userID any, role any) *MockDomainStore_IsDomainAllowed_Call {
	return &MockDomainStore_IsDomainAllowed_Call{Call: _e.mock.On("IsDomainAllowed", ctx, domain, userID, role)}
}

func (_c *MockDomainStore_IsDomainAllowed_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID, role int16)) *MockDomainStore_IsDomainAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int16
		if args[3] != nil {
			arg3 = args[3].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDomainStore_IsDomainAllowed_Call) Return(b bool, err error) *MockDomainStore_IsDomainAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDomainStore_IsDomainAllowed_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID, role int16) (bool, error)) *MockDomainStore_IsDomainAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomains provides a mock function for the type MockDomainStore
func (_mock *MockDomainStore) ListDomains(ctx context.Context, userID uuid.UUID, role int16) ([]tunnel.Domain, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ListDomains")
	}

	var r0 []tunnel.Domain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int16) ([]tunnel.Domain, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int16) []tunnel.Domain); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.Domain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int16) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainStore_ListDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomains'
type MockDomainStore_ListDomains_Call struct {
	*mock.Call
}

// ListDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - role int16
func (_e *MockDomainStore_Expecter) ListDomains(ctx any, userID any, role any) *MockDomainStore_ListDomains_Call {
	return &MockDomainStore_ListDomains_Call{Call: _e.mock.On("ListDomains", ctx, userID, role)}
}

func (_c *MockDomainStore_ListDomains_Call) Run(run func(ctx context.Context, userID uuid.UUID, role int16)) *MockDomainStore_ListDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int16
		if args[2] != nil {
			arg2 = args[2].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDomainStore_ListDomains_Call) Return(domains []tunnel.Domain, err error) *MockDomainStore_ListDomains_Call {
	_c.Call.Return(domains, err)
	return _c
}

func (_c *MockDomainStore_ListDomains_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, role int16) ([]tunnel.Domain, error)) *MockDomainStore_ListDomains_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockDomainStore
func (_mock *MockDomainStore) Ping(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockDomainStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDomainStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDomainStore_Expecter) Ping(ctx any) *MockDomainStore_Ping_Call {
	return &MockDomainStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDomainStore_Ping_Call) Run(run func(ctx context.Context)) *MockDomainStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDomainStore_Ping_Call) Return() *MockDomainStore_Ping_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDomainStore_Ping_Call) RunAndReturn(run func(ctx context.Context)) *MockDomainStore_Ping_Call {
	_c.Run(run)
	return _c
}

// RemoveDomain provides a mock function for the type MockDomainStore
func (_mock *MockDomainStore) RemoveDomain(ctx context.Context, domain string, userID uuid.UUID, role int16) error {
	ret := _mock.Called(ctx, domain, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int16) error); ok {
		r0 = returnFunc(ctx, domain, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainStore_RemoveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDomain'
type MockDomainStore_RemoveDomain_Call struct {
	*mock.Call
}

// RemoveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - userID uuid.UUID
//   - role int16
func (_e *MockDomainStore_Expecter) RemoveDomain(ctx any, domain any, userID any, role any) *MockDomainStore_RemoveDomain_Call {
	return &MockDomainStore_RemoveDomain_Call{Call: _e.mock.On("RemoveDomain", ctx, domain, userID, role)}
}

func (_c *MockDomainStore_RemoveDomain_Call) Run(run func(ctx context.Context, domain string, userID uuid.UUID, role int16)) *MockDomainStore_RemoveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int16
		if args[3] != nil {
			arg3 = args[3].(int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDomainStore_RemoveDomain_Call) Return(err error) *MockDomainStore_RemoveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainStore_RemoveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, userID uuid.UUID, role int16) error) *MockDomainStore_RemoveDomain_Call {
	_c.Call.Return(run)
	return _c
}
