// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHostRegistry creates a new instance of MockHostRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostRegistry {
	mock := &MockHostRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostRegistry is an autogenerated mock type for the HostRegistry type
type MockHostRegistry struct {
	mock.Mock
}

type MockHostRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostRegistry) EXPECT() *MockHostRegistry_Expecter {
	return &MockHostRegistry_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) Authorize(host string) {
	_mock.Called(host)
	return
}

// MockHostRegistry_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockHostRegistry_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) Authorize(host any) *MockHostRegistry_Authorize_Call {
	return &MockHostRegistry_Authorize_Call{Call: _e.mock.On("Authorize", host)}
}

func (_c *MockHostRegistry_Authorize_Call) Run(run func(host string)) *MockHostRegistry_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_Authorize_Call) Return() *MockHostRegistry_Authorize_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHostRegistry_Authorize_Call) RunAndReturn(run func(host string)) *MockHostRegistry_Authorize_Call {
	_c.Run(run)
	return _c
}

// Deauthorize provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) Deauthorize(host string) {
	_mock.Called(host)
	return
}

// MockHostRegistry_Deauthorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deauthorize'
type MockHostRegistry_Deauthorize_Call struct {
	*mock.Call
}

// Deauthorize is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) Deauthorize(host any) *MockHostRegistry_Deauthorize_Call {
	return &MockHostRegistry_Deauthorize_Call{Call: _e.mock.On("Deauthorize", host)}
}

func (_c *MockHostRegistry_Deauthorize_Call) Run(run func(host string)) *MockHostRegistry_Deauthorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_Deauthorize_Call) Return() *MockHostRegistry_Deauthorize_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHostRegistry_Deauthorize_Call) RunAndReturn(run func(host string)) *MockHostRegistry_Deauthorize_Call {
	_c.Run(run)
	return _c
}

// IsActive provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) IsActive(host string) bool {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHostRegistry_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type MockHostRegistry_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) IsActive(host any) *MockHostRegistry_IsActive_Call {
	return &MockHostRegistry_IsActive_Call{Call: _e.mock.On("IsActive", host)}
}

func (_c *MockHostRegistry_IsActive_Call) Run(run func(host string)) *MockHostRegistry_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_IsActive_Call) Return(b bool) *MockHostRegistry_IsActive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHostRegistry_IsActive_Call) RunAndReturn(run func(host string) bool) *MockHostRegistry_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// IsAuthorized provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) IsAuthorized(host string) bool {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthorized")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHostRegistry_IsAuthorized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAuthorized'
type MockHostRegistry_IsAuthorized_Call struct {
	*mock.Call
}

// IsAuthorized is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) IsAuthorized(host any) *MockHostRegistry_IsAuthorized_Call {
	return &MockHostRegistry_IsAuthorized_Call{Call: _e.mock.On("IsAuthorized", host)}
}

func (_c *MockHostRegistry_IsAuthorized_Call) Run(run func(host string)) *MockHostRegistry_IsAuthorized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_IsAuthorized_Call) Return(b bool) *MockHostRegistry_IsAuthorized_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHostRegistry_IsAuthorized_Call) RunAndReturn(run func(host string) bool) *MockHostRegistry_IsAuthorized_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllowed provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) ListAllowed() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAllowed")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockHostRegistry_ListAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllowed'
type MockHostRegistry_ListAllowed_Call struct {
	*mock.Call
}

// ListAllowed is a helper method to define mock.On call
func (_e *MockHostRegistry_Expecter) ListAllowed() *MockHostRegistry_ListAllowed_Call {
	return &MockHostRegistry_ListAllowed_Call{Call: _e.mock.On("ListAllowed")}
}

func (_c *MockHostRegistry_ListAllowed_Call) Run(run func()) *MockHostRegistry_ListAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostRegistry_ListAllowed_Call) Return(strings []string) *MockHostRegistry_ListAllowed_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockHostRegistry_ListAllowed_Call) RunAndReturn(run func() []string) *MockHostRegistry_ListAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) Register(host string) bool {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHostRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHostRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) Register(host any) *MockHostRegistry_Register_Call {
	return &MockHostRegistry_Register_Call{Call: _e.mock.On("Register", host)}
}

func (_c *MockHostRegistry_Register_Call) Run(run func(host string)) *MockHostRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_Register_Call) Return(b bool) *MockHostRegistry_Register_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHostRegistry_Register_Call) RunAndReturn(run func(host string) bool) *MockHostRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type MockHostRegistry
func (_mock *MockHostRegistry) Unregister(host string) {
	_mock.Called(host)
	return
}

// MockHostRegistry_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockHostRegistry_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - host string
func (_e *MockHostRegistry_Expecter) Unregister(host any) *MockHostRegistry_Unregister_Call {
	return &MockHostRegistry_Unregister_Call{Call: _e.mock.On("Unregister", host)}
}

func (_c *MockHostRegistry_Unregister_Call) Run(run func(host string)) *MockHostRegistry_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostRegistry_Unregister_Call) Return() *MockHostRegistry_Unregister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHostRegistry_Unregister_Call) RunAndReturn(run func(host string)) *MockHostRegistry_Unregister_Call {
	_c.Run(run)
	return _c
}
