// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/tunnel"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnelStore creates a new instance of MockTunnelStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnelStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnelStore {
	mock := &MockTunnelStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnelStore is an autogenerated mock type for the TunnelStore type
type MockTunnelStore struct {
	mock.Mock
}

type MockTunnelStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnelStore) EXPECT() *MockTunnelStore_Expecter {
	return &MockTunnelStore_Expecter{mock: &_m.Mock}
}

// DeleteRateLimitSetting provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) DeleteRateLimitSetting(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRateLimitSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_DeleteRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRateLimitSetting'
type MockTunnelStore_DeleteRateLimitSetting_Call struct {
	*mock.Call
}

// DeleteRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockTunnelStore_Expecter) DeleteRateLimitSetting(ctx any, username any) *MockTunnelStore_DeleteRateLimitSetting_Call {
	return &MockTunnelStore_DeleteRateLimitSetting_Call{Call: _e.mock.On("DeleteRateLimitSetting", ctx, username)}
}

func (_c *MockTunnelStore_DeleteRateLimitSetting_Call) Run(run func(ctx context.Context, username string)) *MockTunnelStore_DeleteRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_DeleteRateLimitSetting_Call) Return(err error) *MockTunnelStore_DeleteRateLimitSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_DeleteRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string) error) *MockTunnelStore_DeleteRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTunnel provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) DeleteTunnel(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_DeleteTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTunnel'
type MockTunnelStore_DeleteTunnel_Call struct {
	*mock.Call
}

// DeleteTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockTunnelStore_Expecter) DeleteTunnel(ctx any, sessionID any) *MockTunnelStore_DeleteTunnel_Call {
	return &MockTunnelStore_DeleteTunnel_Call{Call: _e.mock.On("DeleteTunnel", ctx, sessionID)}
}

func (_c *MockTunnelStore_DeleteTunnel_Call) Run(run func(ctx context.Context, sessionID string)) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_DeleteTunnel_Call) Return(err error) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_DeleteTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockTunnelStore_DeleteTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// FlushAllTunnelsAndDomains provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) FlushAllTunnelsAndDomains(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushAllTunnelsAndDomains")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_FlushAllTunnelsAndDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushAllTunnelsAndDomains'
type MockTunnelStore_FlushAllTunnelsAndDomains_Call struct {
	*mock.Call
}

// FlushAllTunnelsAndDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) FlushAllTunnelsAndDomains(ctx any) *MockTunnelStore_FlushAllTunnelsAndDomains_Call {
	return &MockTunnelStore_FlushAllTunnelsAndDomains_Call{Call: _e.mock.On("FlushAllTunnelsAndDomains", ctx)}
}

func (_c *MockTunnelStore_FlushAllTunnelsAndDomains_Call) Run(run func(ctx context.Context)) *MockTunnelStore_FlushAllTunnelsAndDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_FlushAllTunnelsAndDomains_Call) Return(err error) *MockTunnelStore_FlushAllTunnelsAndDomains_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_FlushAllTunnelsAndDomains_Call) RunAndReturn(run func(ctx context.Context) error) *MockTunnelStore_FlushAllTunnelsAndDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimitSetting provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) GetRateLimitSetting(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimitSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_GetRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimitSetting'
type MockTunnelStore_GetRateLimitSetting_Call struct {
	*mock.Call
}

// GetRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockTunnelStore_Expecter) GetRateLimitSetting(ctx any, username any) *MockTunnelStore_GetRateLimitSetting_Call {
	return &MockTunnelStore_GetRateLimitSetting_Call{Call: _e.mock.On("GetRateLimitSetting", ctx, username)}
}

func (_c *MockTunnelStore_GetRateLimitSetting_Call) Run(run func(ctx context.Context, username string)) *MockTunnelStore_GetRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_GetRateLimitSetting_Call) Return(s string, err error) *MockTunnelStore_GetRateLimitSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTunnelStore_GetRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockTunnelStore_GetRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockTunnelStore_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTunnelStore_Expecter) IsTokenRevoked(ctx any, token any) *MockTunnelStore_IsTokenRevoked_Call {
	return &MockTunnelStore_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, token)}
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) Run(run func(ctx context.Context, token string)) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) Return(b bool, err error) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTunnelStore_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockTunnelStore_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ListTunnels provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) ListTunnels(ctx context.Context) ([]tunnel.TunnelInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTunnels")
	}

	var r0 []tunnel.TunnelInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]tunnel.TunnelInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []tunnel.TunnelInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.TunnelInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_ListTunnels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTunnels'
type MockTunnelStore_ListTunnels_Call struct {
	*mock.Call
}

// ListTunnels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) ListTunnels(ctx any) *MockTunnelStore_ListTunnels_Call {
	return &MockTunnelStore_ListTunnels_Call{Call: _e.mock.On("ListTunnels", ctx)}
}

func (_c *MockTunnelStore_ListTunnels_Call) Run(run func(ctx context.Context)) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_ListTunnels_Call) Return(tunnelInfos []tunnel.TunnelInfo, err error) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Return(tunnelInfos, err)
	return _c
}

func (_c *MockTunnelStore_ListTunnels_Call) RunAndReturn(run func(ctx context.Context) ([]tunnel.TunnelInfo, error)) *MockTunnelStore_ListTunnels_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) Ping(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTunnelStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockTunnelStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) Ping(ctx any) *MockTunnelStore_Ping_Call {
	return &MockTunnelStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockTunnelStore_Ping_Call) Run(run func(ctx context.Context)) *MockTunnelStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_Ping_Call) Return() *MockTunnelStore_Ping_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTunnelStore_Ping_Call) RunAndReturn(run func(ctx context.Context)) *MockTunnelStore_Ping_Call {
	_c.Run(run)
	return _c
}

// PublishInspectEvent provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) PublishInspectEvent(ctx context.Context, host string, payload string) error {
	ret := _mock.Called(ctx, host, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishInspectEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, host, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_PublishInspectEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishInspectEvent'
type MockTunnelStore_PublishInspectEvent_Call struct {
	*mock.Call
}

// PublishInspectEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
//   - payload string
func (_e *MockTunnelStore_Expecter) PublishInspectEvent(ctx any, host any, payload any) *MockTunnelStore_PublishInspectEvent_Call {
	return &MockTunnelStore_PublishInspectEvent_Call{Call: _e.mock.On("PublishInspectEvent", ctx, host, payload)}
}

func (_c *MockTunnelStore_PublishInspectEvent_Call) Run(run func(ctx context.Context, host string, payload string)) *MockTunnelStore_PublishInspectEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_PublishInspectEvent_Call) Return(err error) *MockTunnelStore_PublishInspectEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_PublishInspectEvent_Call) RunAndReturn(run func(ctx context.Context, host string, payload string) error) *MockTunnelStore_PublishInspectEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PublishTunnelEvent provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) PublishTunnelEvent(ctx context.Context, eventType string) error {
	ret := _mock.Called(ctx, eventType)

	if len(ret) == 0 {
		panic("no return value specified for PublishTunnelEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, eventType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_PublishTunnelEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTunnelEvent'
type MockTunnelStore_PublishTunnelEvent_Call struct {
	*mock.Call
}

// PublishTunnelEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
func (_e *MockTunnelStore_Expecter) PublishTunnelEvent(ctx any, eventType any) *MockTunnelStore_PublishTunnelEvent_Call {
	return &MockTunnelStore_PublishTunnelEvent_Call{Call: _e.mock.On("PublishTunnelEvent", ctx, eventType)}
}

func (_c *MockTunnelStore_PublishTunnelEvent_Call) Run(run func(ctx context.Context, eventType string)) *MockTunnelStore_PublishTunnelEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_PublishTunnelEvent_Call) Return(err error) *MockTunnelStore_PublishTunnelEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_PublishTunnelEvent_Call) RunAndReturn(run func(ctx context.Context, eventType string) error) *MockTunnelStore_PublishTunnelEvent_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshActiveDomains provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RefreshActiveDomains(ctx context.Context, domains []string, sessionID string, ttl time.Duration) error {
	ret := _mock.Called(ctx, domains, sessionID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RefreshActiveDomains")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, domains, sessionID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RefreshActiveDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshActiveDomains'
type MockTunnelStore_RefreshActiveDomains_Call struct {
	*mock.Call
}

// RefreshActiveDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - domains []string
//   - sessionID string
//   - ttl time.Duration
func (_e *MockTunnelStore_Expecter) RefreshActiveDomains(ctx any, domains any, sessionID any, ttl any) *MockTunnelStore_RefreshActiveDomains_Call {
	return &MockTunnelStore_RefreshActiveDomains_Call{Call: _e.mock.On("RefreshActiveDomains", ctx, domains, sessionID, ttl)}
}

func (_c *MockTunnelStore_RefreshActiveDomains_Call) Run(run func(ctx context.Context, domains []string, sessionID string, ttl time.Duration)) *MockTunnelStore_RefreshActiveDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RefreshActiveDomains_Call) Return(err error) *MockTunnelStore_RefreshActiveDomains_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RefreshActiveDomains_Call) RunAndReturn(run func(ctx context.Context, domains []string, sessionID string, ttl time.Duration) error) *MockTunnelStore_RefreshActiveDomains_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveActiveDomain provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RemoveActiveDomain(ctx context.Context, domain string) error {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for RemoveActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RemoveActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveActiveDomain'
type MockTunnelStore_RemoveActiveDomain_Call struct {
	*mock.Call
}

// RemoveActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockTunnelStore_Expecter) RemoveActiveDomain(ctx any, domain any) *MockTunnelStore_RemoveActiveDomain_Call {
	return &MockTunnelStore_RemoveActiveDomain_Call{Call: _e.mock.On("RemoveActiveDomain", ctx, domain)}
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) Run(run func(ctx context.Context, domain string)) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) Return(err error) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RemoveActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string) error) *MockTunnelStore_RemoveActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RevokeToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockTunnelStore_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTunnelStore_Expecter) RevokeToken(ctx any, token any) *MockTunnelStore_RevokeToken_Call {
	return &MockTunnelStore_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, token)}
}

func (_c *MockTunnelStore_RevokeToken_Call) Run(run func(ctx context.Context, token string)) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RevokeToken_Call) Return(err error) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTunnelStore_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeUserTokens provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) RevokeUserTokens(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_RevokeUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserTokens'
type MockTunnelStore_RevokeUserTokens_Call struct {
	*mock.Call
}

// RevokeUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTunnelStore_Expecter) RevokeUserTokens(ctx any, userID any) *MockTunnelStore_RevokeUserTokens_Call {
	return &MockTunnelStore_RevokeUserTokens_Call{Call: _e.mock.On("RevokeUserTokens", ctx, userID)}
}

func (_c *MockTunnelStore_RevokeUserTokens_Call) Run(run func(ctx context.Context, userID string)) *MockTunnelStore_RevokeUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelStore_RevokeUserTokens_Call) Return(err error) *MockTunnelStore_RevokeUserTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_RevokeUserTokens_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockTunnelStore_RevokeUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveDomain provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetActiveDomain(ctx context.Context, domain string, sessionID string) error {
	ret := _mock.Called(ctx, domain, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, domain, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetActiveDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveDomain'
type MockTunnelStore_SetActiveDomain_Call struct {
	*mock.Call
}

// SetActiveDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - sessionID string
func (_e *MockTunnelStore_Expecter) SetActiveDomain(ctx any, domain any, sessionID any) *MockTunnelStore_SetActiveDomain_Call {
	return &MockTunnelStore_SetActiveDomain_Call{Call: _e.mock.On("SetActiveDomain", ctx, domain, sessionID)}
}

func (_c *MockTunnelStore_SetActiveDomain_Call) Run(run func(ctx context.Context, domain string, sessionID string)) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetActiveDomain_Call) Return(err error) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetActiveDomain_Call) RunAndReturn(run func(ctx context.Context, domain string, sessionID string) error) *MockTunnelStore_SetActiveDomain_Call {
	_c.Call.Return(run)
	return _c
}

// SetRateLimitSetting provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetRateLimitSetting(ctx context.Context, username string, value string) error {
	ret := _mock.Called(ctx, username, value)

	if len(ret) == 0 {
		panic("no return value specified for SetRateLimitSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetRateLimitSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRateLimitSetting'
type MockTunnelStore_SetRateLimitSetting_Call struct {
	*mock.Call
}

// SetRateLimitSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - value string
func (_e *MockTunnelStore_Expecter) SetRateLimitSetting(ctx any, username any, value any) *MockTunnelStore_SetRateLimitSetting_Call {
	return &MockTunnelStore_SetRateLimitSetting_Call{Call: _e.mock.On("SetRateLimitSetting", ctx, username, value)}
}

func (_c *MockTunnelStore_SetRateLimitSetting_Call) Run(run func(ctx context.Context, username string, value string)) *MockTunnelStore_SetRateLimitSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetRateLimitSetting_Call) Return(err error) *MockTunnelStore_SetRateLimitSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetRateLimitSetting_Call) RunAndReturn(run func(ctx context.Context, username string, value string) error) *MockTunnelStore_SetRateLimitSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SetToken provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetToken(ctx context.Context, userID string, token string, expiration time.Duration) error {
	ret := _mock.Called(ctx, userID, token, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, userID, token, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type MockTunnelStore_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - token string
//   - expiration time.Duration
func (_e *MockTunnelStore_Expecter) SetToken(ctx any, userID any, token any, expiration any) *MockTunnelStore_SetToken_Call {
	return &MockTunnelStore_SetToken_Call{Call: _e.mock.On("SetToken", ctx, userID, token, expiration)}
}

func (_c *MockTunnelStore_SetToken_Call) Run(run func(ctx context.Context, userID string, token string, expiration time.Duration)) *MockTunnelStore_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetToken_Call) Return(err error) *MockTunnelStore_SetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetToken_Call) RunAndReturn(run func(ctx context.Context, userID string, token string, expiration time.Duration) error) *MockTunnelStore_SetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetTunnel provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SetTunnel(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error {
	ret := _mock.Called(ctx, sessionID, info)

	if len(ret) == 0 {
		panic("no return value specified for SetTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, tunnel.TunnelInfo) error); ok {
		r0 = returnFunc(ctx, sessionID, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelStore_SetTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTunnel'
type MockTunnelStore_SetTunnel_Call struct {
	*mock.Call
}

// SetTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - info tunnel.TunnelInfo
func (_e *MockTunnelStore_Expecter) SetTunnel(ctx any, sessionID any, info any) *MockTunnelStore_SetTunnel_Call {
	return &MockTunnelStore_SetTunnel_Call{Call: _e.mock.On("SetTunnel", ctx, sessionID, info)}
}

func (_c *MockTunnelStore_SetTunnel_Call) Run(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo)) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 tunnel.TunnelInfo
		if args[2] != nil {
			arg2 = args[2].(tunnel.TunnelInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SetTunnel_Call) Return(err error) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelStore_SetTunnel_Call) RunAndReturn(run func(ctx context.Context, sessionID string, info tunnel.TunnelInfo) error) *MockTunnelStore_SetTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeInspectEvents provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SubscribeInspectEvents(ctx context.Context, hosts ...string) (<-chan string, error) {
	var tmpRet mock.Arguments
	if len(hosts) > 0 {
		tmpRet = _mock.Called(ctx, hosts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SubscribeInspectEvents")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (<-chan string, error)); ok {
		return returnFunc(ctx, hosts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) <-chan string); ok {
		r0 = returnFunc(ctx, hosts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, hosts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_SubscribeInspectEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeInspectEvents'
type MockTunnelStore_SubscribeInspectEvents_Call struct {
	*mock.Call
}

// SubscribeInspectEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - hosts ...string
func (_e *MockTunnelStore_Expecter) SubscribeInspectEvents(ctx any, hosts ...any) *MockTunnelStore_SubscribeInspectEvents_Call {
	return &MockTunnelStore_SubscribeInspectEvents_Call{Call: _e.mock.On("SubscribeInspectEvents",
		append([]any{ctx}, hosts...)...)}
}

func (_c *MockTunnelStore_SubscribeInspectEvents_Call) Run(run func(ctx context.Context, hosts ...string)) *MockTunnelStore_SubscribeInspectEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SubscribeInspectEvents_Call) Return(stringCh <-chan string, err error) *MockTunnelStore_SubscribeInspectEvents_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockTunnelStore_SubscribeInspectEvents_Call) RunAndReturn(run func(ctx context.Context, hosts ...string) (<-chan string, error)) *MockTunnelStore_SubscribeInspectEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTunnelEvents provides a mock function for the type MockTunnelStore
func (_mock *MockTunnelStore) SubscribeTunnelEvents(ctx context.Context) (<-chan string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTunnelEvents")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnelStore_SubscribeTunnelEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTunnelEvents'
type MockTunnelStore_SubscribeTunnelEvents_Call struct {
	*mock.Call
}

// SubscribeTunnelEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnelStore_Expecter) SubscribeTunnelEvents(ctx any) *MockTunnelStore_SubscribeTunnelEvents_Call {
	return &MockTunnelStore_SubscribeTunnelEvents_Call{Call: _e.mock.On("SubscribeTunnelEvents", ctx)}
}

func (_c *MockTunnelStore_SubscribeTunnelEvents_Call) Run(run func(ctx context.Context)) *MockTunnelStore_SubscribeTunnelEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnelStore_SubscribeTunnelEvents_Call) Return(stringCh <-chan string, err error) *MockTunnelStore_SubscribeTunnelEvents_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockTunnelStore_SubscribeTunnelEvents_Call) RunAndReturn(run func(ctx context.Context) (<-chan string, error)) *MockTunnelStore_SubscribeTunnelEvents_Call {
	_c.Call.Return(run)
	return _c
}
