name: Manual Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - release
      acme_env:
        description: "ACME directory"
        required: false
        default: production
        type: choice
        options:
          - production
          - staging
      cli_version:
        description: "CLI Client Version override (leave blank for auto tag / 'dev')"
        required: false
        type: string

env:
  CLI_VERSION: ${{ github.event.inputs.cli_version != '' && github.event.inputs.cli_version || (github.ref_type == 'tag' && github.ref_name || 'dev') }}

jobs:

  # ========== MANUAL DEV ==========
  build-dev:
    if: ${{ github.event.inputs.target == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/gotunnel:dev
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy-dev:
    if: ${{ github.event.inputs.target == 'dev' }}
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build Clients
        run: |
          docker run --rm -v $(pwd):/app -w /app -e SERVER_URL="https://${{ secrets.WEBUI_DOMAIN }}" -e VERSION="${{ env.CLI_VERSION }}" golang:1.26-alpine sh -c "apk add --no-cache make && make build-clients"
      - name: Copy binaries to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "downloads/"
          target: "."
      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            IMAGE=ghcr.io/${{ github.repository_owner }}/gotunnel:dev
            ACME_ENV="${{ github.event.inputs.acme_env }}"
            if [ -z "$ACME_ENV" ]; then ACME_ENV=production; fi
            sudo podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}
            sudo podman pull $IMAGE

            sudo mkdir -p cert-cache

            CERT_CONTENT="${{ secrets.WILDCARD_CERT_CONTENT }}"
            KEY_CONTENT="${{ secrets.WILDCARD_KEY_CONTENT }}"
            
            if [ -n "$CERT_CONTENT" ] && [ -n "$KEY_CONTENT" ]; then
              echo "Memasang certificate wildcard dari GitHub Secrets..."
              echo "$CERT_CONTENT" | sudo tee cert-cache/cloudflare-cert.pem > /dev/null
              echo "$KEY_CONTENT" | sudo tee cert-cache/cloudflare-key.pem > /dev/null
            fi

            sudo podman stop tunnel || true
            sudo podman rm tunnel || true
            sudo podman run -d --name tunnel -p 80:80 -p 443:443 \
              -v "$(pwd)/cert-cache:/app/cert-cache:Z" \
              -v "$(pwd)/downloads:/app/downloads:Z" \
              -e GATEWAY_DOMAIN=${{ secrets.GATEWAY_DOMAIN }} \
              -e TUNNEL_DOMAIN=${{ secrets.TUNNEL_DOMAIN }} \
              -e ACME_ENABLE="${{ secrets.ACME_ENABLE }}" \
              -e ACME_ENV="$ACME_ENV" \
              -e CLI_LATEST_VERSION="${{ env.CLI_VERSION }}" \
              -e REDIS_ADDR="host.containers.internal:6379" \
              -e REDIS_DB="0" \
              -e DOMAIN_REDIS_DB="1" \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e WILDCARD_DOMAIN=${{ secrets.WILDCARD_DOMAIN }} \
              -e WILDCARD_CERT_PATH="/app/cert-cache/cloudflare-cert.pem" \
              -e WILDCARD_KEY_PATH="/app/cert-cache/cloudflare-key.pem" \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
              -e WEBUI_DOMAIN=${{ secrets.WEBUI_DOMAIN }} \
              -e WEBUI_PORT=${{ secrets.WEBUI_PORT }} \
              $IMAGE

            echo "⏳ Menunggu container booting (5 detik)..."
            sleep 5
            STATUS=$(sudo podman inspect -f '{{.State.Status}}' tunnel)
            if [ "$STATUS" != "running" ]; then
              echo "❌ Error: Deployment GAGAL! Container crash/berhenti (Status: $STATUS)."
              sudo podman logs tunnel
              exit 1
            else
              echo "✅ Sukses: Deployment BERHASIL! Container berjalan dengan sehat."
              echo "--- Log Terakhir ---"
              sudo podman logs tunnel | tail -n 20
            fi



  # ======== MANUAL RELEASE =======
  build-release:
    if: ${{ github.event.inputs.target == 'release' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setver.outputs.version }}
    steps:

      - uses: actions/checkout@v7

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Specify VERSION:
      # - If ref is TAG → use auto tag
      # - If not TAG → use input version
      - name: Tentukan VERSION otomatis/manual
        id: setver
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "Auto VERSION from TAG: ${GITHUB_REF_NAME}"
          else
            echo "ERROR: Release job harus dijalankan dari Git TAG."
            exit 1
          fi

      - name: Build & Push Release Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/gotunnel:${VERSION}
          docker build -t $IMAGE .
          docker tag $IMAGE ghcr.io/${{ github.repository_owner }}/gotunnel:latest
          docker push $IMAGE
          docker push ghcr.io/${{ github.repository_owner }}/gotunnel:latest


  deploy-release:
    if: ${{ github.event.inputs.target == 'release' }}
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build Clients
        run: |
          docker run --rm -v $(pwd):/app -w /app -e SERVER_URL="https://${{ secrets.WEBUI_DOMAIN }}" -e VERSION="${{ env.CLI_VERSION }}" golang:1.26-alpine sh -c "apk add --no-cache make && make build-clients"
      - name: Copy binaries to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "downloads/"
          target: "."
      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            VERSION="${{ needs.build-release.outputs.version }}"
            IMAGE=ghcr.io/${{ github.repository_owner }}/gotunnel:${VERSION}
            ACME_ENV="${{ github.event.inputs.acme_env }}"
            if [ -z "$ACME_ENV" ]; then ACME_ENV=production; fi
            sudo podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}
            sudo podman pull $IMAGE
            
            sudo mkdir -p cert-cache

            CERT_CONTENT="${{ secrets.WILDCARD_CERT_CONTENT }}"
            KEY_CONTENT="${{ secrets.WILDCARD_KEY_CONTENT }}"
            
            if [ -n "$CERT_CONTENT" ] && [ -n "$KEY_CONTENT" ]; then
              echo "Memasang certificate wildcard dari GitHub Secrets..."
              echo "$CERT_CONTENT" | sudo tee cert-cache/cloudflare-cert.pem > /dev/null
              echo "$KEY_CONTENT" | sudo tee cert-cache/cloudflare-key.pem > /dev/null
            fi

            sudo podman stop tunnel || true
            sudo podman rm tunnel || true
            sudo podman run -d --name tunnel -p 80:80 -p 443:443 \
              -v "$(pwd)/cert-cache:/app/cert-cache:Z" \
              -v "$(pwd)/downloads:/app/downloads:Z" \
              -e GATEWAY_DOMAIN=${{ secrets.GATEWAY_DOMAIN }} \
              -e TUNNEL_DOMAIN=${{ secrets.TUNNEL_DOMAIN }} \
              -e ACME_ENABLE="${{ secrets.ACME_ENABLE }}" \
              -e ACME_ENV="$ACME_ENV" \
              -e CLI_LATEST_VERSION="${{ env.CLI_VERSION }}" \
              -e REDIS_ADDR="host.containers.internal:6379" \
              -e REDIS_DB="0" \
              -e DOMAIN_REDIS_DB="1" \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e WILDCARD_DOMAIN=${{ secrets.WILDCARD_DOMAIN }} \
              -e WILDCARD_CERT_PATH="/app/cert-cache/cloudflare-cert.pem" \
              -e WILDCARD_KEY_PATH="/app/cert-cache/cloudflare-key.pem" \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
              -e WEBUI_DOMAIN=${{ secrets.WEBUI_DOMAIN }} \
              -e WEBUI_PORT=${{ secrets.WEBUI_PORT }} \
              $IMAGE

            echo "⏳ Menunggu container booting (5 detik)..."
            sleep 5
            STATUS=$(sudo podman inspect -f '{{.State.Status}}' tunnel)
            if [ "$STATUS" != "running" ]; then
              echo "❌ Error: Deployment GAGAL! Container crash/berhenti (Status: $STATUS)."
              sudo podman logs tunnel
              exit 1
            else
              echo "✅ Sukses: Deployment BERHASIL! Container berjalan dengan sehat."
              echo "--- Log Terakhir ---"
              sudo podman logs tunnel | tail -n 20
            fi
