// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gotunnel/internal/domain/apikey"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// CountActiveByUserID provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) CountActiveByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByUserID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_CountActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByUserID'
type MockAPIKeyRepository_CountActiveByUserID_Call struct {
	*mock.Call
}

// CountActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIKeyRepository_Expecter) CountActiveByUserID(ctx any, userID any) *MockAPIKeyRepository_CountActiveByUserID_Call {
	return &MockAPIKeyRepository_CountActiveByUserID_Call{Call: _e.mock.On("CountActiveByUserID", ctx, userID)}
}

func (_c *MockAPIKeyRepository_CountActiveByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIKeyRepository_CountActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_CountActiveByUserID_Call) Return(n int, err error) *MockAPIKeyRepository_CountActiveByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAPIKeyRepository_CountActiveByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockAPIKeyRepository_CountActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Create(ctx context.Context, key *apikey.APIKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apikey.APIKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key *apikey.APIKey
func (_e *MockAPIKeyRepository_Expecter) Create(ctx any, key any) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, key)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, key *apikey.APIKey)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apikey.APIKey
		if args[1] != nil {
			arg1 = args[1].(*apikey.APIKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(err error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, key *apikey.APIKey) error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsActiveByName provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) ExistsActiveByName(ctx context.Context, userID uuid.UUID, name string) (bool, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsActiveByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_ExistsActiveByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsActiveByName'
type MockAPIKeyRepository_ExistsActiveByName_Call struct {
	*mock.Call
}

// ExistsActiveByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
func (_e *MockAPIKeyRepository_Expecter) ExistsActiveByName(ctx any, userID any, name any) *MockAPIKeyRepository_ExistsActiveByName_Call {
	return &MockAPIKeyRepository_ExistsActiveByName_Call{Call: _e.mock.On("ExistsActiveByName", ctx, userID, name)}
}

func (_c *MockAPIKeyRepository_ExistsActiveByName_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string)) *MockAPIKeyRepository_ExistsActiveByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_ExistsActiveByName_Call) Return(b bool, err error) *MockAPIKeyRepository_ExistsActiveByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPIKeyRepository_ExistsActiveByName_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, name string) (bool, error)) *MockAPIKeyRepository_ExistsActiveByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) GetByHash(ctx context.Context, keyHash string) (*apikey.APIKey, error) {
	ret := _mock.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *apikey.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*apikey.APIKey, error)); ok {
		return returnFunc(ctx, keyHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *apikey.APIKey); ok {
		r0 = returnFunc(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockAPIKeyRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockAPIKeyRepository_Expecter) GetByHash(ctx any, keyHash any) *MockAPIKeyRepository_GetByHash_Call {
	return &MockAPIKeyRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, keyHash)}
}

func (_c *MockAPIKeyRepository_GetByHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByHash_Call) Return(aPIKey *apikey.APIKey, err error) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_GetByHash_Call) RunAndReturn(run func(ctx context.Context, keyHash string) (*apikey.APIKey, error)) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) GetByID(ctx context.Context, id uuid.UUID) (*apikey.APIKey, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *apikey.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*apikey.APIKey, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *apikey.APIKey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAPIKeyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAPIKeyRepository_Expecter) GetByID(ctx any, id any) *MockAPIKeyRepository_GetByID_Call {
	return &MockAPIKeyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAPIKeyRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByID_Call) Return(aPIKey *apikey.APIKey, err error) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*apikey.APIKey, error)) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) ListAll(ctx context.Context, limit int, offset int, usernameFilter string) ([]apikey.APIKeyWithOwner, int, error) {
	ret := _mock.Called(ctx, limit, offset, usernameFilter)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []apikey.APIKeyWithOwner
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) ([]apikey.APIKeyWithOwner, int, error)); ok {
		return returnFunc(ctx, limit, offset, usernameFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) []apikey.APIKeyWithOwner); ok {
		r0 = returnFunc(ctx, limit, offset, usernameFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apikey.APIKeyWithOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string) int); ok {
		r1 = returnFunc(ctx, limit, offset, usernameFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = returnFunc(ctx, limit, offset, usernameFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeyRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockAPIKeyRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - usernameFilter string
func (_e *MockAPIKeyRepository_Expecter) ListAll(ctx any, limit any, offset any, usernameFilter any) *MockAPIKeyRepository_ListAll_Call {
	return &MockAPIKeyRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, limit, offset, usernameFilter)}
}

func (_c *MockAPIKeyRepository_ListAll_Call) Run(run func(ctx context.Context, limit int, offset int, usernameFilter string)) *MockAPIKeyRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_ListAll_Call) Return(aPIKeyWithOwners []apikey.APIKeyWithOwner, n int, err error) *MockAPIKeyRepository_ListAll_Call {
	_c.Call.Return(aPIKeyWithOwners, n, err)
	return _c
}

func (_c *MockAPIKeyRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, usernameFilter string) ([]apikey.APIKeyWithOwner, int, error)) *MockAPIKeyRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]apikey.APIKey, int, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []apikey.APIKey
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]apikey.APIKey, int, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []apikey.APIKey); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeyRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockAPIKeyRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockAPIKeyRepository_Expecter) ListByUserID(ctx any, userID any, limit any, offset any) *MockAPIKeyRepository_ListByUserID_Call {
	return &MockAPIKeyRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) Return(aPIKeys []apikey.APIKey, n int, err error) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Return(aPIKeys, n, err)
	return _c
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]apikey.APIKey, int, error)) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeyRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAPIKeyRepository_Expecter) Revoke(ctx any, id any) *MockAPIKeyRepository_Revoke_Call {
	return &MockAPIKeyRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockAPIKeyRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) Return(err error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) RevokeAllByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type MockAPIKeyRepository_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIKeyRepository_Expecter) RevokeAllByUserID(ctx any, userID any) *MockAPIKeyRepository_RevokeAllByUserID_Call {
	return &MockAPIKeyRepository_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *MockAPIKeyRepository_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIKeyRepository_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_RevokeAllByUserID_Call) Return(err error) *MockAPIKeyRepository_RevokeAllByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_RevokeAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockAPIKeyRepository_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUsedAt provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) UpdateLastUsedAt(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsedAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_UpdateLastUsedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUsedAt'
type MockAPIKeyRepository_UpdateLastUsedAt_Call struct {
	*mock.Call
}

// UpdateLastUsedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAPIKeyRepository_Expecter) UpdateLastUsedAt(ctx any, id any) *MockAPIKeyRepository_UpdateLastUsedAt_Call {
	return &MockAPIKeyRepository_UpdateLastUsedAt_Call{Call: _e.mock.On("UpdateLastUsedAt", ctx, id)}
}

func (_c *MockAPIKeyRepository_UpdateLastUsedAt_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAPIKeyRepository_UpdateLastUsedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_UpdateLastUsedAt_Call) Return(err error) *MockAPIKeyRepository_UpdateLastUsedAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_UpdateLastUsedAt_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAPIKeyRepository_UpdateLastUsedAt_Call {
	_c.Call.Return(run)
	return _c
}
